# Site settings
title: Mozilla Campus Clubs
email: participation@mozilla.com
description: >
    Get involved with the Campus initiatives at Mozilla
baseurl: "/mozilla-campus-clubs"
url: "https://mozilla.github.io"
twitter_username: mozparticipate
github_username:  mozilla

# Build settings
markdown: kramdown
